export const types = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
